update scripts

diff --git a/scripts/nodejs_install b/scripts/nodejs_install
--- a/scripts/nodejs_install
+++ b/scripts/nodejs_install
@@ -17,6 +17,9 @@ initiateVariables
 rm -f $RC_NODENV_VERSION_FILE
 rm -rf $RC_NODENV_NPM_DIR
 
+BUILD_LOGFILE="/tmp/$VERSION.log"
+BUILD_OPTS_FILE="/tmp/$VERSION.config"
+
 if [ "true" == "${SKIP_BUILD}" ]; then
 	echo "skip build"
 	eval "$(nodenv init -)"
@@ -42,23 +45,32 @@ else
 	NODEJS_CFLAGS=""
 	NODEJS_CXXFLAGS=""
 
-	# Prepare installation script
+	# Build it.
 	#
-	TMP=$(mktemp)
-
-	NODE_BUILD_CACHE_PATH=/tmp \
-		CONFIGURE_OPTS="${NODEJS_CONFIGURE_OPTS} ${CONFIGURE_OPTS}" \
+	echo "build log: ${BUILD_LOGFILE}"
+	CONFIGURE_OPTS="${NODEJS_CONFIGURE_OPTS} ${CONFIGURE_OPTS}" \
 		MAKE_OPTS="-j$OS_CPUS" \
 		CFLAGS="${NODEJS_CFLAGS} ${CFLAGS}" \
 		CXXFLAGS="${NODEJS_CXXFLAGS} ${CXXFLAGS}" \
-		nodenv install $VERSION
+		nodenv install $VERSION --verbose > ${BUILD_LOGFILE} 2>&1
 	[ "0" != "$?" ] && echo "failed to build nodejs $VERSION" && exit 1
+
+	rm -f ${BUILD_OPTS_FILE}
+	echo -e "CONFIGURE_OPTS\t\"${NODEJS_CONFIGURE_OPTS} ${CONFIGURE_OPTS}\"" >> ${BUILD_OPTS_FILE}
+	echo -e "CFLAGS\t\"${NODEJS_CFLAGS} ${CFLAGS}\"" >> ${BUILD_OPTS_FILE}
+	echo -e "CXXFLAGS\t\"${NODEJS_CXXFLAGS} ${CXXFLAGS}\"" >> ${BUILD_OPTS_FILE}
 fi
 
 # Switch to the built version
 #
 nodenv local $VERSION
 [ "0" != "$?" ] && echo "failed to switch to nodejs $VERSION" && exit 1
+
+# Make sure nodejs engine can be launched normally after build
+#
+node -p process.config > /dev/null 2>&1
+[ "0" != "$?" ] && echo "failed to launch nodejs instance: $VERSION" && exit 1
+
 
 if [ "" != "${MODULES}" ]; then
 	MODULES=($(echo $MODULES | tr ',' '\n'))
@@ -86,8 +98,18 @@ else
 	#
 	echo "copying to $RC_NODE_WORKDIR ..."
 	cp $RC_NODENV_ROOT $RC_NODE_WORKDIR -R
+
+	# Store settings at the workdir
+	# 
+	VERSION=$VERSION \
+		MODULES=$2 \
+		BUILD_OPTS_FILE=$BUILD_OPTS_FILE \
+		NPM_VERSION=$(npm --version) \
+		BUILD_LOGFILE=$BUILD_LOGFILE \
+		storeSettings
 fi
 
 # Clean-up all building results
 #
 [ "true" != "${SKIP_CLEANUP}" ] && cleanup
+exit 0
